### ISSUE TITLE
How can I write my own video driver?

### ISSUE THREAD

**Issue by VapourDev** [fpmurphy/UEFI-Utilities-2019#6] opened 2021-05-13 10:30 UTC
_While developing an OS,_
 
**1. How can I write own like VESA and GOP ( own graphics video driver )?
2. Is windows and others uses VESA and GOP?**

**Comment by fpmurphy** [comment] 2022-02-08 08:48
I am closing this. It is not a bug report.

**Closed as completed by fpmurphy** 2022-02-08 08:48 UTC
